"""Initial migration

Revision ID: 90eba67b6e92
Revises: 
Create Date: 2024-09-06 15:09:47.642186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90eba67b6e92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('skins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('champion_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['champion_name'], ['champions.name'], ),
    sa.PrimaryKeyConstraint('id', 'champion_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skins')
    op.drop_table('champions')
    # ### end Alembic commands ###
